import Img from '../public/Placeholder.jpg';

export const products = [
    {
      id: "1",
      name: "Duende Painting",
      description: "beware of the duende",
      price: 2999,
      brand: "Monobrand",
      category: "Category A",
      inStock: true,
      images: [
        {
          color: "White",
          colorCode: "#FFFFFF",
          image:Img.src,
        },
        {
          color: "Gray",
          colorCode: "#808080",
          image:Img.src,
        },
      ],
      reviews: [],
    },
    {
      id: "2",
      name: "Mono Painting",
      description: "monos de lab",
      price: 102.99,
      brand: "Monobrand",
      category: "Category B",
      inStock: true,
      images: [
        {
          color: "Black",
          colorCode: "#000000",
          imag:Img.src,
        },
      ],
      reviews: [
        {
          id: "1",
          userId: "1",
          productId: "2",
          rating: 5,
          comment: "ta wenarda",
          createdDate: "2023-07-06T06:08:33.067Z",
          user: {
            id: "1",
            name: "ElMatoi",
            email: "example@gmail.com",
            emailVerified: null,
            image:Img.src,
            hashedPassword: null,
            createdAt: "2023-05-30T08:08:53.979Z",
            updatedAt: "2023-05-30T08:08:53.979Z",
            role: "ADMIN",
          },
        },
      ],
    },
    {
      id: "3",
      name: "Mono en mesa redonda",
      description: "mono en mesa redonda",
      price: 100,
      brand: "Monobrand",
      category: "Category C",
      inStock: true,
      images: [
        {
          color: "Black",
          colorCode: "#000000",
          image:Img.src,
        },
        {
          color: "Blue",
          colorCode: " #0000FF",
          image:Img.src,
        },
        {
          color: "Red",
          colorCode: "#FF0000",
          image:Img.src,
        },
      ],
      reviews: [
        {
          id: "2",
          userId: "2",
          productId: "3",
          rating: 4,
          comment:
            "mono en mesa redonda bottom text",
          createdDate: "2023-06-26T15:53:44.483Z",
          user: {
            id: "2",
            name: "Carlosweed",
            email: "example1@gmail.com",
            emailVerified: null,
            image:Img.src,
            hashedPassword: null,
            createdAt: "2023-06-26T15:40:52.558Z",
            updatedAt: "2023-06-26T15:40:52.558Z",
            role: "USER",
          },
        },
        {
          id: "3",
          userId: "1",
          productId: "3",
          rating: 4,
          comment: "top text mono mesa redonda",
          createdDate: "2023-06-26T14:30:40.998Z",
          user: {
            id: "1",
            name: "ElMatoi",
            email: "example@gmail.com",
            emailVerified: null,
            image:Img.src,
            hashedPassword: null,
            createdAt: "2023-05-30T08:08:53.979Z",
            updatedAt: "2023-05-30T08:08:53.979Z",
            role: "ADMIN",
          },
        },
      ],
    },
    {
      id: "4",
      name: "duende comiendo pan",
      description:"duende tenebroso comiendo sendo pan",
      price: 70,
      brand: "Monobrand",
      category: "Category A",
      inStock: true,
      images: [
        {
          color: "Graphite",
          colorCode: " #383838",
          image:Img.src,
        },
      ],
      reviews: [],
    },
    {
      id: "5",
      name: 'Mono y duende peleando con cuchillos',
      description:"pelea mundial",
      price: 50,
      brand: "Monobrand",
      category: "Category B",
      inStock: true,
      images: [
        {
          color: "Black",
          colorCode: "#000000",
          image:Img.src,
        },
        {
          color: "Silver",
          colorCode: "#C0C0C0",
          image:Img.src,
        },
      ],
      reviews: [],
    },
    {
      id: "6",
      name: 'Duendelablaberolab',
      description:"labinglab",
      price: 50000,
      brand: "Monobrand",
      category: "Category C",
      inStock: true,
      images: [
        {
          color: "Black",
          colorCode: "#000000",
          image:Img.src,
        },
        {
          color: "Silver",
          colorCode: "#C0C0C0",
          image:Img.src,
        },
      ],
      reviews: [],
    },
  ];